import Navbar from '@/components/Navbar'
import { Inter } from 'next/font/google'
import './main.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div className='bod'>
          <div className='all'>
            <Navbar />
            <div className='pac'>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
